sudo: required
services:
  - docker
  
before_install:
  - docker build -t ssimonitch/docker-react -f Dockerfile.dev .
  
script:
  - docker run ssimointch/docker-react npm run test -- --coverage